In [1]:
# numpy와 구조와 유사


In [2]:
import torch

In [3]:
# array
t = torch.tensor([[1, 2], [3, 4]])
print(t)

tensor([[1, 2],
        [3, 4]])


In [4]:
# device지정 가능
t = torch.tensor([[1, 2], [3, 4]]).to('cuda')
print(t)

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [5]:
# numpy식 활용
t = torch.randn((10, 5), device='cuda:0')
print(t)

tensor([[-0.5883, -0.1474, -0.7099, -1.4472, -1.0602],
        [-1.2955,  0.3825, -0.5695,  1.1973, -0.3110],
        [-0.9132,  0.5954,  1.1320, -0.0829,  0.4293],
        [ 2.3079,  0.0471, -0.1226, -0.3316, -1.3072],
        [ 0.5390,  0.1712,  0.2173,  0.3701,  2.4910],
        [ 0.9170, -0.9865, -0.4171,  0.1479, -1.4853],
        [-0.3761,  0.4062,  0.7181, -1.3299,  1.3960],
        [-0.6728, -0.8166, -1.1655,  0.4529,  0.4060],
        [-1.4782, -1.3895, -0.9368, -0.0076,  1.2932],
        [-0.7273,  0.3605, -0.0262,  0.3513,  0.2505]], device='cuda:0')


In [6]:
t = torch.arange(10)
print(t)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
t = torch.zeros((10, 5), device='cuda')
print(t)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')


In [8]:
# indexing
arr = torch.randn((10, 5))
arr

tensor([[ 0.5960, -1.5463,  0.4828, -0.5172,  0.0159],
        [ 1.5150, -0.8969,  0.4426,  1.7285, -0.0045],
        [ 1.0102, -1.0401, -1.8276, -0.3329, -0.7693],
        [ 0.8269,  1.0692,  0.2010,  0.0701,  0.9364],
        [ 1.7851, -2.3989,  0.5132,  2.1660,  0.8646],
        [ 0.3569,  0.2197, -1.5368,  0.8422, -0.6610],
        [-0.0400, -1.2425,  0.2685, -0.0042,  2.0364],
        [-0.2930, -2.2015,  0.6197, -0.2731,  0.2771],
        [-1.6907, -1.9589,  0.0139,  0.5474, -0.6932],
        [-0.7808,  0.0067, -0.6201, -1.0121, -1.1787]])

In [9]:
arr[0:5, 1:2]

tensor([[-1.5463],
        [-0.8969],
        [-1.0401],
        [ 1.0692],
        [-2.3989]])

In [10]:
arr[1, 3]

tensor(1.7285)

In [11]:
arr[1][3]

tensor(1.7285)

In [12]:
arr[arr > 0]

tensor([0.5960, 0.4828, 0.0159, 1.5150, 0.4426, 1.7285, 1.0102, 0.8269, 1.0692,
        0.2010, 0.0701, 0.9364, 1.7851, 0.5132, 2.1660, 0.8646, 0.3569, 0.2197,
        0.8422, 0.2685, 2.0364, 0.6197, 0.2771, 0.0139, 0.5474, 0.0067])

In [13]:
# 대수연산
# dot: 내적
# mv: 행렬-벡터곱
# mm: 행렬-행렬곱
# matmul: auto모드


In [14]:
v = torch.Tensor([1, 2, 1, 3])
m = torch.Tensor([
    [1, 1, 2, 2],
    [3, 1, 2, 1],
    [1, 1, 0, 0],
    [5, 2, 1, 1]
])

print(torch.mv(m, v))

tensor([11., 10.,  3., 13.])


In [15]:
print(torch.matmul(v, m))
print(torch.matmul(m, v))

tensor([23., 10.,  9.,  7.])
tensor([11., 10.,  3., 13.])
